spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tiendavirtual?serverTimezone=UTC
    username: root
    password: admin

# Propiedades para que hibernate cree adecuadamente las instrucciones SQL
  jpa:
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      
server:
  port: 8000
